# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170124_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='tasks', to='todo.Tag'),
        ),
    ]
