# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('todo', '0003_auto_20170124_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auth.Group'),
        ),
    ]
