# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20170124_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
    ]
