# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task_iscomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_complete',
            field=models.DateTimeField(null=True),
        ),
    ]
